services:
  - type: web
    name: assemble-dataflow-collection
    env: node
    buildCommand: "cd backend && npm install && cd ../frontend && npm install --include=dev && npm run build"
    startCommand: "cd backend && node server.js"
    envVars:
      - key: NODE_VERSION
        value: ~20
      - key: PORT
        value: "5000"
      - key: MONGO_URI
        value: "mongodb+srv://assembleAdmin:Asdf0987@ringassemble.wgoopau.mongodb.net/?appName=RingAssemble"
      - key: COHERE_API_KEY
        value: "IwVTZ9pLgqLCiUoaAEMptAnm2szSmiFUIVMhlKlZ"
